{
 "title": "Copilot Usage Advanced Dashboard",
 "tags": [ "copilot" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organization_name",
    "label": "Organization",
    "query": "{\"find\": \"terms\", \"field\":  \"organization_slug\", \"query\": \"organization_slug:*\"}"
   },
   {
    "name": "team_name",
    "label": "Team",
    "query": "{\"find\": \"terms\", \"field\":  \"team_slug\", \"query\": \"team_slug:*\"}"
   },
   {
    "name": "language_name",
    "label": "Language",
    "query": "{\"find\": \"terms\", \"field\":  \"language\", \"query\": \"language:*\"}"
   },
   {
    "name": "editor_name",
    "label": "Editor",
    "query": "{\"find\": \"terms\", \"field\":  \"editor\", \"query\": \"editor:*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Copilot Seat Info & Top Languages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Copilot Plan Type",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "plan_type",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "organization_slug: $organization_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "seat_total", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Active in this Cycle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "seat_active_this_cycle", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Inactive in this Cycle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "seat_inactive_this_cycle", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "For 📖tutorials & 💖feedback, please visit the repo \"Copilot Usage Advanced Dashboard\", Click👉",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 }
  },
  {
   "title": "Total Active & Chat Users (Sum of Every Teams, Nested teams may cause duplicate calculations. For solutions, refer to the link above)",
   "type": "barchart",
   "description": "If teams are nested, there may be duplicate calculations. Please refer to the tutorial information above.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "total_active_chat_users", "id": "1", "settings": { "script": "_value * -1" }, "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    },
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total_active_users",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Added this Cycle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "seat_added_this_cycle", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Pending Invation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "seat_pending_invitation", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Pending Cancellation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "seat_pending_cancellation", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Ranking of User Inactive Days ",
   "type": "barchart",
   "gridPos": { "h": 24, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "assignee_login",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "days_since_last_activity", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND days_since_last_activity: [1 TO *]",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Number of Never Active Users",
   "type": "table",
   "gridPos": { "h": 24, "w": 3, "x": 5, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "assignee_login",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "days_since_last_activity", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND days_since_last_activity: [-1 TO -1]",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Top Languages by Accepted Rate (Count)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Top Languages by Suggested Count",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "language",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "suggestions_count", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name AND language: $language_name AND editor: $editor_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Top Languages by Accepted Rate (Lines)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Top Languages by Suggested Lines",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "language",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "lines_suggested", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name AND language: $language_name AND editor: $editor_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Top Teams by Accepted Rate (Count)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Top Teams by Suggested Count",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "team_slug",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "suggestions_count", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name AND language: $language_name AND editor: $editor_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Top Teams by Accepted Rate (Lines)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Top Teams by Suggested Lines",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "team_slug",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "lines_suggested", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name AND language: $language_name AND editor: $editor_name",
     "timeField": "day"
    }
   ]
  },
  { "title": "Copilot Usage Total Insight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Total Accept & Suggest Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "total_acceptances_count", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    },
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_suggestions_count", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Average Accepted Rate (Count)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Cumulative Number of Accepted Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "organization_slug",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "total_acceptances_count", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Cumulative Number of Suggestions Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "organization_slug",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "total_suggestions_count", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Average Accepted Rate (Lines)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Cumulative Number of Accepted Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "organization_slug",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "total_lines_accepted", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Cumulative Number of Suggestions Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "organization_slug",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "total_lines_suggested", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Total Accept & Suggest Lines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "total_lines_accepted", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    },
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_lines_suggested", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Average Accepted Rate (Chat)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Cumulative Number of Accepted Chats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "organization_slug",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "total_chat_acceptances", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Cumulative Number of  Chat Turns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "organization_slug",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "total_chat_turns", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Total Accept Rate by Count & Lines & Chat Turns",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B ", "type": "math" },
    { "expression": "$C / $D", "type": "math" },
    { "expression": "$E / $F", "type": "math" }
   ]
  },
  {
   "title": "Total Accept & Chat Turns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "total_chat_acceptances", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    },
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_chat_turns", "id": "1", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Copilot Usage Breakdown Insight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Editors Breakdown",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "editor",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "acceptances_count", "id": "1", "type": "sum" },
      { "field": "suggestions_count", "id": "3", "type": "sum" },
      { "field": "lines_accepted", "id": "4", "type": "sum" },
      { "field": "lines_suggested", "id": "5", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name AND language: $language_name AND editor: $editor_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Languages Breakdown",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "language",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "acceptances_count", "id": "1", "type": "sum" },
      { "field": "suggestions_count", "id": "3", "type": "sum" },
      { "field": "lines_accepted", "id": "4", "type": "sum" },
      { "field": "lines_suggested", "id": "5", "type": "sum" }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name AND language: $language_name AND editor: $editor_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Active Users Count (Group by Language)",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "language",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "active_users",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name AND language: $language_name AND editor: $editor_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Active Users Count (Group by Editor)",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "editor",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "day",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "active_users",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "organization_slug: $organization_name AND team_slug: $team_name AND language: $language_name AND editor: $editor_name",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Accept Rate by Count (%)",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Accept Rate by Count(%)",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Accept Rate by Lines (%)",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A / $B *100", "type": "math" }
   ]
  },
  {
   "title": "Accept Rate by Lines (%)",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A / $B *100", "type": "math" }
   ]
  }
 ]
}